/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Bookmark } from './models/bookmark';
export type { BookmarkResult } from './models/bookmark-result';
export type { Comment } from './models/comment';
export type { CommentResponse } from './models/comment-response';
export type { CreatePostRequest } from './models/create-post-request';
export type { Like } from './models/like';
export type { LikeResponse } from './models/like-response';
export type { NotificationDto } from './models/notification-dto';
export type { PagedModelCommentResponse } from './models/paged-model-comment-response';
export type { PagedModelPost } from './models/paged-model-post';
export type { PageMetadata } from './models/page-metadata';
export type { Post } from './models/post';
