/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GroupMemberDto {
  admin?: boolean;
  coAdmin?: boolean;
  createdBy?: string;
  createdDate?: string;
  groupId?: number;
  id?: number;
  status?: string;
  userId?: string;
}
