/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GroupDto {
  archived?: boolean;
  createdBy?: string;
  createdDate?: string;
  description?: string;
  id?: number;
  memberCount?: number;
  name?: string;
  subject?: string;
}
