/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GroupPostDto {
  content?: string;
  createdBy?: string;
  createdDate?: string;
  fileName?: string;
  filePath?: string;
  groupId?: number;
  id?: number;
  state?: 'PUBLISHED' | 'DELETED';
  type?: 'TEXT' | 'IMAGE' | 'VIDEO' | 'AUDIO' | 'DOCUMENT' | 'LINK';
  userId?: string;
}
