services:
  postgres:
    image: postgres:15
    container_name: postgres-sql-wac
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: anas
      POSTGRES_PASSWORD: anas
      POSTGRES_DB: keycloak
      POSTGRES_HOST_AUTH_METHOD: scram-sha-256
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U anas -d keycloak" ]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin4:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - 8888:80
    environment:
      PGADMIN_DEFAULT_EMAIL: anas.lahboub@edu.uiz.ac.ma
      PGADMIN_DEFAULT_PASSWORD: root
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres

  keycloak:
    image: quay.io/keycloak/keycloak:23.0
    container_name: keycloak
    restart: always
    command:
      - start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: anas
      KC_DB_PASSWORD: anas
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HEALTH_ENABLED: true
    ports:
      - 8080:8080
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      # Volume for persisting Keycloak data
      - keycloak_data:/opt/keycloak/data
    healthcheck:
      test: [ "CMD-SHELL", "curl -f http://localhost:8080/health || exit 1" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

#  chat-service:
#    build: ./chat-service
#    container_name: chat-service
#    restart: always
#    ports:
#      - 8081:8080
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#    depends_on:
#      - postgres
#    volumes:
#      - ./chat-service:/app

  redis:
    image: redis:7
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]
    volumes:
      - redis_data:/data


volumes:
  postgres_data:
  pgadmin_data:
  # Named volume for Keycloak data persistence
  keycloak_data:
  redis_data: