/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { SaveMessage$Params } from './fn/message/save-message';
export { saveMessage } from './fn/message/save-message';
export type { SetMessageToSeen$Params } from './fn/message/set-message-to-seen';
export { setMessageToSeen } from './fn/message/set-message-to-seen';
export type { UploadMedia$Params } from './fn/message/upload-media';
export { uploadMedia } from './fn/message/upload-media';
export type { GetAllMessages$Params } from './fn/message/get-all-messages';
export { getAllMessages } from './fn/message/get-all-messages';
export type { GetChatsByReceiver$Params } from './fn/chats/get-chats-by-receiver';
export { getChatsByReceiver } from './fn/chats/get-chats-by-receiver';
export type { CreateChat$Params } from './fn/chats/create-chat';
export { createChat } from './fn/chats/create-chat';
export type { GetAllUsers$Params } from './fn/user/get-all-users';
export { getAllUsers } from './fn/user/get-all-users';
