/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GroupMemberDto } from '../../models/group-member-dto';

export interface GetGroupMembers$Params {
  groupId: number;
}

export function getGroupMembers(http: HttpClient, rootUrl: string, params: GetGroupMembers$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GroupMemberDto>>> {
  const rb = new RequestBuilder(rootUrl, getGroupMembers.PATH, 'get');
  if (params) {
    rb.path('groupId', params.groupId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GroupMemberDto>>;
    })
  );
}

getGroupMembers.PATH = '/api/groups/{groupId}/members';
