# ============================================
# application-docker.yml (Post Service)
# Crée ce fichier: post-service/src/main/resources/application-docker.yml
# ============================================

spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/post-db
    username: anas
    password: anas

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myapp
          jwk-set-uri: http://keycloak:8080/realms/myapp/protocol/openid-connect/certs

  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

# Communication inter-services
chat:
  service:
    url: http://chat-service:8081