/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GroupMemberDto } from '../../models/group-member-dto';

export interface DesignateCoAdmin$Params {
  groupId: number;
  userId: string;
}

export function designateCoAdmin(http: HttpClient, rootUrl: string, params: DesignateCoAdmin$Params, context?: HttpContext): Observable<StrictHttpResponse<GroupMemberDto>> {
  const rb = new RequestBuilder(rootUrl, designateCoAdmin.PATH, 'post');
  if (params) {
    rb.path('groupId', params.groupId, {});
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<GroupMemberDto>;
    })
  );
}

designateCoAdmin.PATH = '/api/v1/groups/{groupId}/members/{userId}/co-admin';
