/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GroupPostDto } from '../../models/group-post-dto';

export interface GetPublishedPostsByUser$Params {
  groupId: number;
  userId: string;
}

export function getPublishedPostsByUser(http: HttpClient, rootUrl: string, params: GetPublishedPostsByUser$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GroupPostDto>>> {
  const rb = new RequestBuilder(rootUrl, getPublishedPostsByUser.PATH, 'get');
  if (params) {
    rb.path('groupId', params.groupId, {});
    rb.path('userId', params.userId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GroupPostDto>>;
    })
  );
}

getPublishedPostsByUser.PATH = '/api/v1/groups/{groupId}/posts/user/{userId}';
