/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { Bookmark } from './models/bookmark';
export type { Comment } from './models/comment';
export type { CreatePostRequest } from './models/create-post-request';
export type { Like } from './models/like';
export type { NotificationDto } from './models/notification-dto';
export type { PagedModelComment } from './models/paged-model-comment';
export type { PagedModelPost } from './models/paged-model-post';
export type { PageMetadata } from './models/page-metadata';
export type { Post } from './models/post';
export type { Vote } from './models/vote';
