/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Post } from '../../models/post';

export interface GetPinnedPosts$Params {
  'group-id': string;
}

export function getPinnedPosts(http: HttpClient, rootUrl: string, params: GetPinnedPosts$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Post>>> {
  const rb = new RequestBuilder(rootUrl, getPinnedPosts.PATH, 'get');
  if (params) {
    rb.path('group-id', params['group-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Post>>;
    })
  );
}

getPinnedPosts.PATH = '/api/v1/posts/pinned/{group-id}';
