/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Comment } from '../../models/comment';

export interface GetReplies$Params {
  'comment-id': number;
}

export function getReplies(http: HttpClient, rootUrl: string, params: GetReplies$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<Comment>>> {
  const rb = new RequestBuilder(rootUrl, getReplies.PATH, 'get');
  if (params) {
    rb.path('comment-id', params['comment-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<Comment>>;
    })
  );
}

getReplies.PATH = '/api/v1/posts/comment/{comment-id}/replies';
