/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedModelComment } from '../../models/paged-model-comment';

export interface GetComments$Params {
  'post-id': number;
  page?: number;
  size?: number;
}

export function getComments(http: HttpClient, rootUrl: string, params: GetComments$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedModelComment>> {
  const rb = new RequestBuilder(rootUrl, getComments.PATH, 'get');
  if (params) {
    rb.path('post-id', params['post-id'], {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedModelComment>;
    })
  );
}

getComments.PATH = '/api/v1/posts/{post-id}/comments';
