/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';


export interface IsPostVotedByUser$Params {
  'post-id': number;
  upvote: boolean;
}

export function isPostVotedByUser(http: HttpClient, rootUrl: string, params: IsPostVotedByUser$Params, context?: HttpContext): Observable<StrictHttpResponse<boolean>> {
  const rb = new RequestBuilder(rootUrl, isPostVotedByUser.PATH, 'get');
  if (params) {
    rb.path('post-id', params['post-id'], {});
    rb.query('upvote', params.upvote, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return (r as HttpResponse<any>).clone({ body: String((r as HttpResponse<any>).body) === 'true' }) as StrictHttpResponse<boolean>;
    })
  );
}

isPostVotedByUser.PATH = '/api/v1/posts/{post-id}/voted';
