/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Bookmark } from '../../models/bookmark';

export interface ToggleBookmark$Params {
  'post-id': number;
}

export function toggleBookmark(http: HttpClient, rootUrl: string, params: ToggleBookmark$Params, context?: HttpContext): Observable<StrictHttpResponse<Bookmark>> {
  const rb = new RequestBuilder(rootUrl, toggleBookmark.PATH, 'post');
  if (params) {
    rb.path('post-id', params['post-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Bookmark>;
    })
  );
}

toggleBookmark.PATH = '/api/v1/posts/{post-id}/bookmark';
