/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Like } from '../../models/like';

export interface ToggleLike$Params {
  'post-id': number;
}

export function toggleLike(http: HttpClient, rootUrl: string, params: ToggleLike$Params, context?: HttpContext): Observable<StrictHttpResponse<Like>> {
  const rb = new RequestBuilder(rootUrl, toggleLike.PATH, 'post');
  if (params) {
    rb.path('post-id', params['post-id'], {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Like>;
    })
  );
}

toggleLike.PATH = '/api/v1/posts/{post-id}/like';
