/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { Vote } from '../../models/vote';

export interface VotePost$Params {
  'post-id': number;
  upvote: boolean;
}

export function votePost(http: HttpClient, rootUrl: string, params: VotePost$Params, context?: HttpContext): Observable<StrictHttpResponse<Vote>> {
  const rb = new RequestBuilder(rootUrl, votePost.PATH, 'post');
  if (params) {
    rb.path('post-id', params['post-id'], {});
    rb.query('upvote', params.upvote, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Vote>;
    })
  );
}

votePost.PATH = '/api/v1/posts/{post-id}/vote';
