# ============================================
# application-docker.yml (Gateway Service)
# Crée ce fichier: gitway-service/src/main/resources/application-docker.yml
# ============================================

spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/group-db
    username: anas
    password: anas
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myapp
          jwk-set-uri: http://keycloak:8080/realms/myapp/protocol/openid-connect/certs

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    prefer-ip-address: true