spring:
  application:
    name: group-service
  datasource:
    url: jdbc:postgresql://localhost:5432/group-db
    username: anas
    password: anas
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myapp
          jwk-set-uri: http://localhost:8080/realms/myapp/protocol/openid-connect/certs

springdoc:
  default-produces-media-type: application/json
server:
  port: 8083