server:
  port: 8082

spring:
  application:
    name: group-service
  datasource:
    url: jdbc:postgresql://localhost:5432/group-db
    username: anas
    password: anas
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/myapp
          jwk-set-uri: http://localhost:8080/realms/myapp/protocol/openid-connect/certs

logging:
  level:
    com.anas.groupservice: DEBUG
    org.springframework.web.socket: DEBUG
    org.springframework.security: DEBUG

# WebSocket configuration
websocket:
  allowed-origins: http://localhost:4200

# Swagger configuration
springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /v3/api-docs