/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CommentResponse {
  authorId?: string;
  content?: string;
  createdDate?: string;
  id?: number;
  parentCommentId?: number;
  postId?: number;
  replies?: Array<any>;
  reply?: boolean;
}
