/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PageMetadata } from '../models/page-metadata';
import { Post } from '../models/post';
export interface PagedModelPost {
  content?: Array<Post>;
  page?: PageMetadata;
}
