/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Comment } from '../models/comment';
import { PageMetadata } from '../models/page-metadata';
export interface PagedModelComment {
  content?: Array<Comment>;
  page?: PageMetadata;
}
