/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Bookmark } from '../models/bookmark';
import { Comment } from '../models/comment';
import { Like } from '../models/like';
import { Vote } from '../models/vote';
export interface Post {
  approved?: boolean;
  authorId?: string;
  bookmarkCount?: number;
  bookmarks?: Array<Bookmark>;
  commentCount?: number;
  comments?: Array<Comment>;
  content?: string;
  createdDate?: string;
  downvoteCount?: number;
  groupId?: string;
  id?: number;
  imageUrl?: string;
  lastModifiedDate?: string;
  likeCount?: number;
  likes?: Array<Like>;
  pending?: boolean;
  pinned?: boolean;
  rejected?: boolean;
  status?: 'PENDING' | 'APPROVED' | 'REJECTED';
  summary?: string;
  upvoteCount?: number;
  votes?: Array<Vote>;
}
