/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Vote {
  createdDate?: string;
  id?: number;
  lastModifiedDate?: string;
  upvote?: boolean;
  userId?: string;
}
