/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { MarkAsRead$Params } from './fn/notification-controller/mark-as-read';
export { markAsRead } from './fn/notification-controller/mark-as-read';
export type { MarkAllAsRead$Params } from './fn/notification-controller/mark-all-as-read';
export { markAllAsRead } from './fn/notification-controller/mark-all-as-read';
export type { GetUserNotifications$Params } from './fn/notification-controller/get-user-notifications';
export { getUserNotifications } from './fn/notification-controller/get-user-notifications';
export type { GetUnreadUserNotifications$Params } from './fn/notification-controller/get-unread-user-notifications';
export { getUnreadUserNotifications } from './fn/notification-controller/get-unread-user-notifications';
export type { GetUnreadNotificationCount$Params } from './fn/notification-controller/get-unread-notification-count';
export { getUnreadNotificationCount } from './fn/notification-controller/get-unread-notification-count';
export type { DeleteNotification$Params } from './fn/notification-controller/delete-notification';
export { deleteNotification } from './fn/notification-controller/delete-notification';
export type { SaveMessage$Params } from './fn/message/save-message';
export { saveMessage } from './fn/message/save-message';
export type { SetMessageToSeen$Params } from './fn/message/set-message-to-seen';
export { setMessageToSeen } from './fn/message/set-message-to-seen';
export type { UploadMedia$Params } from './fn/message/upload-media';
export { uploadMedia } from './fn/message/upload-media';
export type { GetAllMessages$Params } from './fn/message/get-all-messages';
export { getAllMessages } from './fn/message/get-all-messages';
export type { GetChatsByReceiver$Params } from './fn/chats/get-chats-by-receiver';
export { getChatsByReceiver } from './fn/chats/get-chats-by-receiver';
export type { CreateChat$Params } from './fn/chats/create-chat';
export { createChat } from './fn/chats/create-chat';
export type { GetAllUsers$Params } from './fn/user/get-all-users';
export { getAllUsers } from './fn/user/get-all-users';
