/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GroupStatisticsDto {
  activeGroups?: number;
  archivedGroups?: number;
  averageMembersPerGroup?: number;
  mostPopularGroupMemberCount?: number;
  mostPopularGroupName?: string;
  totalGroups?: number;
  totalMembers?: number;
}
