/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface Comment {
  approved?: boolean;
  authorId?: string;
  content?: string;
  createdDate?: string;
  id?: number;
  lastModifiedDate?: string;
}
