/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Like } from '../models/like';
export interface LikeResponse {
  action?: string;
  like?: Like;
  likeCount?: number;
  liked?: boolean;
}
