/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NotificationDto {
  createdDate?: string;
  id?: number;
  lastModifiedDate?: string;
  message?: string;
  postContent?: string;
  postId?: number;
  read?: boolean;
  relatedEntityId?: number;
  relatedEntityType?: string;
  type?: string;
  userId?: string;
  userName?: string;
}
