/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CommentResponse } from '../models/comment-response';
import { PageMetadata } from '../models/page-metadata';
export interface PagedModelCommentResponse {
  content?: Array<CommentResponse>;
  page?: PageMetadata;
}
