# ============================================
# application-docker.yml (Gateway Service)
# Crée ce fichier: gitway-service/src/main/resources/application-docker.yml
# ============================================

spring:
  config:
    activate:
      on-profile: docker

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    prefer-ip-address: true