/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { CommentResponse } from '../../models/comment-response';

export interface AddComment$Params {
  postId: number;
  content: string;
  parentCommentId?: number;
}

export function addComment(http: HttpClient, rootUrl: string, params: AddComment$Params, context?: HttpContext): Observable<StrictHttpResponse<CommentResponse>> {
  const rb = new RequestBuilder(rootUrl, addComment.PATH, 'post');
  if (params) {
    rb.path('postId', params.postId, {});
    rb.query('content', params.content, {});
    rb.query('parentCommentId', params.parentCommentId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<CommentResponse>;
    })
  );
}

addComment.PATH = '/api/v1/posts/{postId}/comments';
