/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedModelCommentResponse } from '../../models/paged-model-comment-response';

export interface GetCommentsPaginated$Params {
  postId: number;
  page?: number;
  size?: number;
}

export function getCommentsPaginated(http: HttpClient, rootUrl: string, params: GetCommentsPaginated$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedModelCommentResponse>> {
  const rb = new RequestBuilder(rootUrl, getCommentsPaginated.PATH, 'get');
  if (params) {
    rb.path('postId', params.postId, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedModelCommentResponse>;
    })
  );
}

getCommentsPaginated.PATH = '/api/v1/posts/{postId}/comments/paginated';
