/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PagedModelPost } from '../../models/paged-model-post';

export interface SearchPosts$Params {
  query: string;
  page?: number;
  size?: number;
}

export function searchPosts(http: HttpClient, rootUrl: string, params: SearchPosts$Params, context?: HttpContext): Observable<StrictHttpResponse<PagedModelPost>> {
  const rb = new RequestBuilder(rootUrl, searchPosts.PATH, 'get');
  if (params) {
    rb.query('query', params.query, {});
    rb.query('page', params.page, {});
    rb.query('size', params.size, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PagedModelPost>;
    })
  );
}

searchPosts.PATH = '/api/v1/posts/search';
