/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GroupDto } from '../../models/group-dto';

export interface GetGroupsByTeacherId$Params {
  teacherId: string;
}

export function getGroupsByTeacherId(http: HttpClient, rootUrl: string, params: GetGroupsByTeacherId$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GroupDto>>> {
  const rb = new RequestBuilder(rootUrl, getGroupsByTeacherId.PATH, 'get');
  if (params) {
    rb.path('teacherId', params.teacherId, {});
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GroupDto>>;
    })
  );
}

getGroupsByTeacherId.PATH = '/api/groups/teacher/{teacherId}';
