/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { GroupDto } from '../../models/group-dto';
import { SearchRequest } from '../../models/search-request';

export interface SearchGroups$Params {
      body: SearchRequest
}

export function searchGroups(http: HttpClient, rootUrl: string, params: SearchGroups$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<GroupDto>>> {
  const rb = new RequestBuilder(rootUrl, searchGroups.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'blob', accept: '*/*', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<GroupDto>>;
    })
  );
}

searchGroups.PATH = '/api/v1/groups/search';
