# ============================================
# application-docker.yml (Chat Service)
# Crée ce fichier: chat-service/src/main/resources/application-docker.yml
# ============================================

spring:
  config:
    activate:
      on-profile: docker

  datasource:
    url: jdbc:postgresql://postgres:5432/chat-db
    username: anas
    password: anas

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/myapp
          jwk-set-uri: http://keycloak:8080/realms/myapp/protocol/openid-connect/certs

  data:
    redis:
      port: 6379
      host: redis
      timeout: 60000

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka