spring:
  application:
    name: chat-service

  datasource:
    url: jdbc:postgresql://postgres:5432/chat-db
    username: anas
    password: anas

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/myapp
          jwk-set-uri: http://keycloak:8080/realms/myapp/protocol/openid-connect/certs

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

  data:
    redis:
      port: 6379
      host: redis
      timeout: 60000

server:
  port: 8081
  tomcat:
    max-http-form-post-size: 1000MB
    max-swallow-size: 1000MB

eureka:
  instance:
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

springdoc:
  default-produces-media-type: application/json
application:
  file:
    uploads:
      media-output-path: ./uploads

